### ISSUE TITLE
Pressing enter at the beginning of a heading throws an error

### ISSUE THREAD

**Issue by ctcuff** [ucfopen/Obojobo#1469] opened 2020-08-18 16:38 UTC
Create a new module (or use an existing module), move your cursor to the start of a heading, and press enter. The heading stays in the same place but is turned into regular text. It also produces an error:

```
Uncaught Error: Cannot get the leaf node at path [0,0] because it refers to a non-leaf node: [object Object]
    at Object.leaf (slate.js:5893)
    at Object.leaf (slate.js:3522)
    at slate.js:9378
    at Object.withoutNormalizing (slate.js:5289)
    at Object._delete [as delete] (slate.js:9212)
    at Object.breakToText (keydown-util.js:141)
    at Object.onKeyDown (editor-registration.js:98)
    at VisualEditor.onKeyDown (visual-editor.js:598)
    at isEventHandled (slate-react.js:29963)
    at slate-react.js:29682
```

**Comment by ctcuff** [comment] 2020-08-18 17:02
You also get the same error from #1396

**Comment by zachberry** [comment] 2020-08-19 20:55
#1472 Will solve this issue temporarily for dev/13, but that change simply creates new Headings when hitting enter. The expected behavior is that, when hitting enter on a heading, the part of the text after the cursor should transform into a regular node.

**Comment by zachberry** [comment] 2020-08-19 21:11
#1472 is merged, patching this for now. But I'm leaving this open for now to track a complete fix with expected behavior - will slot for dev/13

**Comment by jpeterson976** [comment] 2020-10-05 17:53
Seems to be working as intended from dev/13 on, hitting enter on a heading will split into a normal text node instead of a second heading, even at the beginning of the heading.

**Closed** 2021-04-09 20:44 UTC
Labels: bug, editor, feels broken, reduce frustration
