### ISSUE TITLE
Dev/16 tests have uncaught errors that need to be fixed

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1658] opened 2021-02-07 03:21 UTC
There's a handful of error types that don't get caught by jest, there's a few occurring on dev/16 test runs as can be seen in these action logs: https://github.com/ucfopen/Obojobo/runs/1847390082?check_suite_focus=true#step:6:1183

**Comment by zachberry** [comment] 2021-04-09 20:35
I believe this is a duplicate of #1667

**Closed by zachberry** 2021-04-09 20:35 UTC
